/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFAZ;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import Clases.ArbolBinario;
import Clases.Comprimir;
import Clases.Descomprimir;
import Clases.ImagenGrafica;
import java.util.HashMap;

/**
 *
 * @author VICTUS
 */
public class ArbolBusqueda extends javax.swing.JFrame {

    ArbolBinario arbol = new ArbolBinario();

    public ArbolBusqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Abrir = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        inOrdBBT = new javax.swing.JButton();
        preOrdBBT = new javax.swing.JButton();
        postBBT = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        BtnIngresar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBtnActualizar = new javax.swing.JButton();
        jBtnArcpers = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTNodos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Lbtiempo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumnos = new javax.swing.JMenu();
        ITEMReportes = new javax.swing.JMenuItem();
        jMEncrypt = new javax.swing.JMenu();
        jMDecrypt = new javax.swing.JMenu();
        Comprimir = new javax.swing.JMenu();
        Descomprimir = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenuItem();
        jMAlumnos1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setText("ARBOL BINARIO DE BUSQUEDA");

        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cargarA.png"))); // NOI18N
        Abrir.setText("Cargar Archivo");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-guardar-30 (1).png"))); // NOI18N
        Guardar.setText("Guardar Documento");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        inOrdBBT.setText("InOrden");
        inOrdBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inOrdBBTActionPerformed(evt);
            }
        });

        preOrdBBT.setText("PreOrden");
        preOrdBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preOrdBBTActionPerformed(evt);
            }
        });

        postBBT.setText("PostOrden");
        postBBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postBBTActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        BtnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Ingresar.png"))); // NOI18N
        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/eliminar.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBtnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/actualizar.png"))); // NOI18N
        jBtnActualizar.setText("Acualizar");
        jBtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualizarActionPerformed(evt);
            }
        });

        jBtnArcpers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-agregar-archivo-30.png"))); // NOI18N
        jBtnArcpers.setText("Cargar Arc. Personalizado");
        jBtnArcpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnArcpersActionPerformed(evt);
            }
        });

        jTNodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "DPI", "Departamento", "Municipio", "Lugar V.", "No. Dosis", "Dosis 1", "Dosis 2", "Dosis 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTNodos);

        jLabel2.setText("Tiempo:");

        Lbtiempo.setText(".");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(0, 4));

        jMAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/menu.png"))); // NOI18N
        jMAlumnos.setText("Menu");
        jMAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        ITEMReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/abb.png"))); // NOI18N
        ITEMReportes.setText("GENERAR IMAGEN");
        ITEMReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEMReportesActionPerformed(evt);
            }
        });
        jMAlumnos.add(ITEMReportes);

        jMEncrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-criptografía-externa-criptografía-relleno-suave-relleno-suave-pez-jugoso-17.png"))); // NOI18N
        jMEncrypt.setText("ENCRYPT");
        jMEncrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMEncryptMousePressed(evt);
            }
        });
        jMEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEncryptActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMEncrypt);

        jMDecrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8-cryptography-17.png"))); // NOI18N
        jMDecrypt.setText("DECRYPT");
        jMDecrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMDecryptMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMDecryptMouseReleased(evt);
            }
        });
        jMDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDecryptActionPerformed(evt);
            }
        });
        jMAlumnos.add(jMDecrypt);

        Comprimir.setText("Comprimir");
        Comprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComprimirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ComprimirMouseReleased(evt);
            }
        });
        Comprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprimirActionPerformed(evt);
            }
        });
        jMAlumnos.add(Comprimir);

        Descomprimir.setText("Descomprimir");
        Descomprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DescomprimirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DescomprimirMouseReleased(evt);
            }
        });
        Descomprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescomprimirActionPerformed(evt);
            }
        });
        jMAlumnos.add(Descomprimir);

        jMenuBar1.add(jMAlumnos);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cerrar.png"))); // NOI18N
        jMenu1.setText("Cerrar");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMSalir);

        jMenuBar1.add(jMenu1);

        jMAlumnos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/regresar.png"))); // NOI18N
        jMAlumnos1.setText("Regresar");
        jMAlumnos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("Regresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMAlumnos1.add(jMenuItem1);

        jMenuBar1.add(jMAlumnos1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(BtnIngresar)
                        .addGap(119, 119, 119)
                        .addComponent(btnBuscar)
                        .addGap(109, 109, 109)
                        .addComponent(jBtnActualizar)
                        .addGap(86, 86, 86)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(preOrdBBT)
                        .addGap(164, 164, 164)
                        .addComponent(inOrdBBT)
                        .addGap(140, 140, 140)
                        .addComponent(postBBT))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Abrir)
                                .addGap(56, 56, 56)
                                .addComponent(jBtnArcpers)
                                .addGap(43, 43, 43)
                                .addComponent(Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lbtiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(221, 221, 221)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Lbtiempo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Abrir)
                            .addComponent(jBtnArcpers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preOrdBBT)
                    .addComponent(inOrdBBT)
                    .addComponent(postBBT))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jBtnActualizar)
                    .addComponent(jButton2))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
        int confirmado = JOptionPane.showConfirmDialog(null, "Está seguro de Salir");
        if (JOptionPane.OK_OPTION == confirmado) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMSalirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if (!arbol.EstaVacio()) {
            int confirmado = JOptionPane.showConfirmDialog(null, "Está seguro de guardar el arbol");
            if (JOptionPane.OK_OPTION == confirmado) {
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("ArbolBinario.txt"))) {
                    String guardado = arbol.guardarPreOrdenTXT(arbol.raiz);
                    writer.write(guardado);
                    JOptionPane.showMessageDialog(null, "Archivo guardado correctamente en la carpeta del proyecto");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio");
        }


    }//GEN-LAST:event_GuardarActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser escogerArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto (.txt)", "txt");
        escogerArchivo.setFileFilter(filtro);
        int valorRetornado = escogerArchivo.showOpenDialog(null);

        if (valorRetornado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = escogerArchivo.getSelectedFile();
            String[] options = {"SI", "NO"};
            int option = JOptionPane.showOptionDialog(null, "¿QUIERES CARGAR TODOS LOS DATOS?", "Selección de Ingreso",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            int cantidad = 0;
            boolean validInput = false;

            // Validación solo números y no texto
            if (option == 1) { // El índice 1 ahora corresponde a "NO"
                while (!validInput) {
                    try {
                        String input = JOptionPane.showInputDialog(null, "¿Cuántos datos quieres cargar?", "Ingreso", JOptionPane.QUESTION_MESSAGE);
                        if (input == null) {
                            return;
                        }
                        cantidad = Integer.parseInt(input);
                        validInput = true;
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            try (BufferedReader br = new BufferedReader(new FileReader(archivoSeleccionado))) {
                String linea;
                StringBuilder txtarea = new StringBuilder();
                int contador = 0;
                while ((linea = br.readLine()) != null) {
                    if (option == 1 && contador >= cantidad) {
                        break;
                    }
                    String[] partes = separarDatosArchivo(linea);
                    if (partes != null) {
                        String nombre = partes[0];
                        long dpi = Long.parseLong(partes[1]);
                        // Ingreso como tal
                        arbol.AgregarNodo(nombre, dpi); // Solo se agrega nombre y DPI
                        contador++;
                    }
                }

                JOptionPane.showMessageDialog(null, "Datos cargados correctamente en el árbol.");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    private static String[] separarDatosArchivo(String linea) {
        // Expresión regular para separar el nombre del DPI
        Pattern pattern = Pattern.compile("(.+?)\\s+(\\d+)");
        Matcher matcher = pattern.matcher(linea);
        if (matcher.matches()) {
            String nombre = matcher.group(1).trim();
            String dpi = matcher.group(2).trim();
            return new String[]{nombre, dpi};
        }
        return null;
    }//GEN-LAST:event_AbrirActionPerformed

    private void inOrdBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inOrdBBTActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTNodos.getModel();
        model.setRowCount(0);

        if (!arbol.EstaVacio()) {
            arbol.InOrden(arbol.raiz, model);

        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio");
        }
    }//GEN-LAST:event_inOrdBBTActionPerformed

    private void preOrdBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preOrdBBTActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTNodos.getModel();
        model.setRowCount(0);

        if (!arbol.EstaVacio()) {
            arbol.PreOrden(arbol.raiz, model);

        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio");
        }
    }//GEN-LAST:event_preOrdBBTActionPerformed

    private void postBBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postBBTActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTNodos.getModel();
        model.setRowCount(0);

        if (!arbol.EstaVacio()) {           
            arbol.PostOrden(arbol.raiz, model);

        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio");
        }
    }//GEN-LAST:event_postBBTActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {

            if (!arbol.EstaVacio()) {
                long dpi = Long.parseLong(JOptionPane.showInputDialog("Ingrese el DPI del nodo a buscar:"));
                DefaultTableModel model = (DefaultTableModel) jTNodos.getModel();
                model.setRowCount(0);
                long startTime = System.nanoTime();
                boolean encontrado = arbol.MostrarNodoBuscado(dpi, model);
                long endTime = System.nanoTime();
                long duration = (endTime - startTime); // duración en nanosegundos
                double duracion = duration / 1_000_000_000.0; // convertir a segundos
                if (encontrado) {
                    Lbtiempo.setText(String.valueOf(duracion) + " s");
                    JOptionPane.showMessageDialog(null, "Nodo encontrado");
                } else {
                    JOptionPane.showMessageDialog(null, "Nodo no encontrado");
                }

            } else {
                JOptionPane.showMessageDialog(null, "El arbol esta vacio");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "DPI a buscar invalido");
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            long numero;
            if (!arbol.EstaVacio()) {
                numero = Long.parseLong(JOptionPane.showInputDialog(null, "Ingresa el Numero de DPI del registro a eliminar", "Eliminando un Nodo", JOptionPane.QUESTION_MESSAGE));
                if (arbol.EliminarNodo(numero) == false) {
                    JOptionPane.showMessageDialog(null, "El Nodo a Eliminar no se encuentra en el Arbol", "Nodo no Encontrado", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "El Nodo ha sido eliminado del Arbol", "Nodo Eliminado", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El Arbol esta vacio", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Nodo a eliminar invalido");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ITEMReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEMReportesActionPerformed
        
        ImagenGrafica MiLienzo = new ImagenGrafica();
        MiLienzo.setArbol(arbol);

        JFrame ventana = new JFrame();
        ventana.getContentPane().add(MiLienzo);
        ventana.setSize(800, 600);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_ITEMReportesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        AgregarDatos ag = new AgregarDatos();
        ag.setVisible(true);
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private static String[] separarDatosArchivoPersonalizado(String linea) {
        // Expresión regular para separar los datos
        Pattern pattern = Pattern.compile("(.+?)\\|([0-9]+)\\|(.+?)\\|(.+?)\\|(.+?)\\|([0-9]+)\\|(.+?)\\|(.+?)\\|(.+)");
        Matcher matcher = pattern.matcher(linea);
        if (matcher.matches()) {
            String[] datos = new String[9];
            for (int i = 0; i < 9; i++) {
                datos[i] = matcher.group(i + 1).trim();
            }
            return datos;
        }
        return null;
    }

    private void jBtnArcpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnArcpersActionPerformed
        JFileChooser escogerArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto (.txt)", "txt");
        escogerArchivo.setFileFilter(filtro);
        int valorRetornado = escogerArchivo.showOpenDialog(null);

        if (valorRetornado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = escogerArchivo.getSelectedFile();
            String[] options = {"SI", "NO"};
            int option = JOptionPane.showOptionDialog(null, "¿QUIERES CARGAR TODOS LOS DATOS?", "Selección de Ingreso",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
            int cantidad = 0;
            boolean validInput = false;

            // Validación solo números y no texto
            if (option == 1) { // El índice 1 ahora corresponde a "NO"
                while (!validInput) {
                    try {
                        String input = JOptionPane.showInputDialog(null, "¿Cuántos datos quieres cargar?", "Ingreso", JOptionPane.QUESTION_MESSAGE);
                        if (input == null) {
                            return;
                        }
                        cantidad = Integer.parseInt(input);
                        validInput = true;
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

            try (BufferedReader br = new BufferedReader(new FileReader(archivoSeleccionado))) {
                String linea;
                int contador = 0;
                while ((linea = br.readLine()) != null) {
                    if (option == 1 && contador >= cantidad) {
                        break;
                    }
                    String[] partes = separarDatosArchivoPersonalizado(linea);
                    if (partes != null) {
                        String nombre = partes[0];
                        long dpi = Long.parseLong(partes[1]);
                        String departamento = partes[2];
                        String municipio = partes[3];
                        String lugarVacunacion = partes[4];
                        int cantidadDosis = Integer.parseInt(partes[5]);
                        String fechaVacuna1 = partes[6];
                        String fechaVacuna2 = partes[7];
                        String fechaVacuna3 = partes[8];

                        arbol.AgregarNodo(nombre, dpi);
                        arbol.actualizarDatos(dpi, nombre, departamento, municipio, lugarVacunacion, cantidadDosis, fechaVacuna1, fechaVacuna2, fechaVacuna3);

                        contador++;
                    }
                }
                JOptionPane.showMessageDialog(null, "Datos cargados correctamente en el árbol.");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jBtnArcpersActionPerformed

    private void jBtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualizarActionPerformed
        ActualizarDatos ag = new ActualizarDatos();
        ag.setVisible(true);
    }//GEN-LAST:event_jBtnActualizarActionPerformed

    private void jMEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEncryptActionPerformed
             
    }//GEN-LAST:event_jMEncryptActionPerformed

    private void jMDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDecryptActionPerformed
    }//GEN-LAST:event_jMDecryptActionPerformed

    private void jMEncryptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMEncryptMousePressed
        if (!arbol.EstaVacio()) {
            int opcion = JOptionPane.showConfirmDialog(null, "Se ecriptaran los datos", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                arbol.encryptRegistro(arbol.raiz, 5);
                JOptionPane.showMessageDialog(null, "Proceso Completado");

            }
        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio");
        }

    }//GEN-LAST:event_jMEncryptMousePressed

    private void jMDecryptMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMDecryptMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMDecryptMouseReleased

    private void jMDecryptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMDecryptMousePressed
        if (!arbol.EstaVacio()) {
            int opcion = JOptionPane.showConfirmDialog(null, "Se decriptaran los datos", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                arbol.decryptRegistro(arbol.raiz, 5);
                JOptionPane.showMessageDialog(null, "Proceso Completado");

            }
        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio");
        }

    }//GEN-LAST:event_jMDecryptMousePressed

    private void ComprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprimirMousePressed
         Comprimir com = new Comprimir();
         String nombre = "ArbolBinario.txt";
         com.comprimirArchivo(nombre);
         
    }//GEN-LAST:event_ComprimirMousePressed

    private void ComprimirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprimirMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ComprimirMouseReleased

    private void ComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComprimirActionPerformed

    private void DescomprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescomprimirMousePressed
      Descomprimir des = new Descomprimir();
      String nombre = "ArbolBinario.txt";
      des.descomprimirArchivo(nombre);
      JOptionPane.showMessageDialog(null, "Descompresion Exitosa", "Descompresion", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_DescomprimirMousePressed

    private void DescomprimirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescomprimirMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_DescomprimirMouseReleased

    private void DescomprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescomprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescomprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArbolBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abrir;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JMenu Comprimir;
    private javax.swing.JMenu Descomprimir;
    private javax.swing.JButton Guardar;
    private javax.swing.JMenuItem ITEMReportes;
    private javax.swing.JLabel Lbtiempo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton inOrdBBT;
    private javax.swing.JButton jBtnActualizar;
    private javax.swing.JButton jBtnArcpers;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMAlumnos;
    private javax.swing.JMenu jMAlumnos1;
    private javax.swing.JMenu jMDecrypt;
    private javax.swing.JMenu jMEncrypt;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTNodos;
    private javax.swing.JButton postBBT;
    private javax.swing.JButton preOrdBBT;
    // End of variables declaration//GEN-END:variables
}
